//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.20 at 04:47:31 PM CET 
//


package at.spengergasse.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="nameCountry1" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="nameCountry2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="years" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nameCountry1",
    "nameCountry2",
    "years"
})
@XmlRootElement(namespace="http://localhost:8080/countries", name = "getCountryGrowthComparisonRequest")
public class GetCountryGrowthComparisonRequest {

    @XmlElement(namespace="http://localhost:8080/countries", required = true)
    protected String nameCountry1;
    @XmlElement(namespace="http://localhost:8080/countries", required = true)
    protected String nameCountry2;
    protected int years;

    /**
     * Gets the value of the nameCountry1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameCountry1() {
        return nameCountry1;
    }

    /**
     * Sets the value of the nameCountry1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameCountry1(String value) {
        this.nameCountry1 = value;
    }

    /**
     * Gets the value of the nameCountry2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameCountry2() {
        return nameCountry2;
    }

    /**
     * Sets the value of the nameCountry2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameCountry2(String value) {
        this.nameCountry2 = value;
    }

    /**
     * Gets the value of the years property.
     * 
     */
    public int getYears() {
        return years;
    }

    /**
     * Sets the value of the years property.
     * 
     */
    public void setYears(int value) {
        this.years = value;
    }

}
